### ISSUE TITLE
Update Courses Cards for Advisors and Student sections

### ISSUE THREAD

**Issue by HyflerSD** [HyflerSD/cybel#39]
In the dashboard for both admin and student, when selecting all courses, there is only static (hard coded data), we need to update those values to match whats in the database.
![image](https://github.com/HyflerSD/cybel/assets/64340578/da8ec40d-8e19-458c-a1b4-e0d6421e84e6)

Here is the file path to this section: 
resources/views/student/courses.blade.php

**Comment by Rolindets** [comment]
Here is how our student course looks now:
![image](https://github.com/HyflerSD/cybel/assets/112668880/e2023198-fb8d-48bd-aa48-30c0273957aa)



here is how our Advisor course looks now:

![image](https://github.com/HyflerSD/cybel/assets/112668880/0d1787d9-e907-4f1b-b83a-9d7636e841a0)

**Comment by HyflerSD** [comment]
@Rolindets dddaaaaaaaaaaaamnnnn

**Comment by patryhernandez0724** [comment]
This is my version fro both, student and admin:
![Screenshot 2024-03-05 at 14-40-59 Laravel Courses](https://github.com/HyflerSD/cybel/assets/91447963/b1ce8797-8a69-4859-8865-1a2f8d4e691
![Screenshot 2024-03-05 at 14-42-20 Laravel Student Courses](https://github.com/HyflerSD/cybel/assets/91447963/5554799c-c42b-4771-8bf3-c3abc5ea6dd2)
4)

**Comment by patryhernandez0724** [comment]
> In the dashboard for both admin and student, when selecting all courses, there is only static (hard coded data), we need to update those values to match whats in the database. ![image](https://private-user-images.githubusercontent.com/64340578/309973273-da8ec40d-8e19-458c-a1b4-e0d6421e84e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzM4NDksIm5iZiI6MTcwOTY3MzU0OSwicGF0aCI6Ii82NDM0MDU3OC8zMDk5NzMyNzMtZGE4ZWM0MGQtOGUxOS00NThjLWExYjQtZTBkNjQyMWU4NGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxMTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODllMjdkMGI0YjQ0ZTZiYTAwMGM0OWNiZDQ4YzE0NmY5NzYxZWI1YzhjNWM0ZDljNjUwYThkMDE2N2MxZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yN-MZV3Y-OpHELYi540HpmhHgY4SF3Zv9Kn-JELi3K0)
> 
> Here is the file path to this section: resources/views/student/courses.blade.php

**Comment by patryhernandez0724** [comment]
closed by mistake
